- name: Deploy ec2 instance on AWS with CloudFormations
  hosts: all
  tasks:
    - name: create a cloudformation stack
      amazon.aws.cloudformation:
        stack_name: "ansible-cloudformation"
        state: "present"
        region: "us-east-2"
        template_body: "{{ lookup('file', 'cf_template.yml') }}"
        tags:
          Stack: "ansible-cloudformation"