- name: Get information on CF Stack
  hosts: localhost
  tasks:
    - name: Get summary information about a stack
      amazon.aws.cloudformation_info:
        stack_name: ansible-cloudformation
        region: "us-east-2"
      register: output

    - debug:
        msg: "{{ output['cloudformation']['ansible-cloudformation'] }}"
